version: "3"
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - utils/.env
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:14-alpine
    env_file:
      - utils/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    env_file:
      - utils/.env
    restart: always
    depends_on:
      - db
      - redis
volumes:
  pgdata:
